### ISSUE TITLE
Delete Command Not Functioning as Per User Guide

### ISSUE THREAD

**Issue by JunLongling** [AY2425S1-CS2103T-F14A-3/tp#125]
The delete n/NAME command is not functioning as described in the user guide. When multiple clients have the same name (e.g., Alfred Lim and Alfred Tan), the command returns "No person with that name found" instead of performing the deletion or suggesting further action

<img width="659" alt="image" src="https://github.com/user-attachments/assets/16f59f0d-6e69-44f8-b6e8-396bd0f555f4">

Steps to Reproduce:
1. Add two clients with the same first name (e.g., Alfred Lim and Alfred Tan).
2. Use the command delete n/Alfred.
3. The app returns "No person with that name found.

Suggested Improvement:
If multiple persons with the same name exist, the app should display a more specific message like:
"Multiple clients with the same name found. Please use delete by ID instead

**Comment by Dinoman44** [comment]
The issue here isn't that the returned message is wrong, but that the `delete` command currently searches for an exact (case-insensitive) match with the name provided.

https://github.com/user-attachments/assets/6949ae52-b621-4ddc-a6fb-743eb6992c95

We could try updating it to allow for word matches instead (so as long as the name query matches a word in the person's name, i.e. first/middle/last name, it gets counted as a match).

I would mainly suggest we update the user guide to reflect what values the `NAME` parameter can take, and how it matches the query to the list of names since it is not clear upon reading how the matching is done.

**Comment by JunLongling** [comment]
Yes we can update the delete section in the user guide
